"""Добавить новую таблицу

Revision ID: ddf80c5a1de4
Revises: 
Create Date: 2023-08-18 11:18:22.180540

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ddf80c5a1de4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('customer_name', sa.Text(), nullable=True),
        sa.Column('customer_email', sa.Text(), nullable=True),
        sa.Column('order_date', sa.TIMESTAMP(), nullable=True),
        sa.Column('total_amount', sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.BigInteger(), nullable=True),
                    sa.Column('referred_by_id', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('referrals',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('referring_user_id', sa.Integer(), nullable=True),
        sa.Column('referred_user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['referred_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['referring_user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )


    op.create_table('sizes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'sub_categories',

        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('products',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('price', sa.Float(), nullable=True),
        sa.Column('image_url', sa.Text(), nullable=True),
        sa.Column('category_id', sa.Integer(), nullable=True),
        sa.Column('sub_category_id', sa.Integer(), nullable=True),
        sa.Column('size_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
        sa.ForeignKeyConstraint(['size_id'], ['sizes.id'], ),
        sa.ForeignKeyConstraint(['sub_category_id'], ['sub_categories.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_table('order_details',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('product_id', sa.Integer(), nullable=True),
        sa.Column('quantity', sa.Integer(), nullable=True),
        sa.Column('subtotal', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_details')
    op.drop_table('products')
    op.drop_table('users')
    op.drop_table('sub_categories')
    op.drop_table('sizes')
    op.drop_table('referrals')
    op.drop_table('orders')
    op.drop_table('categories')
    # ### end Alembic commands ###
